version: "3.9"
   
services:
  backend:
    image: backend-crud:latest
    ports:
      - "5000:5000"
    # volumes:
      # - ./data/db:/var/lib/postgresql/data
    # environment:
    #   - POSTGRES_NAME=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
  web:
    image: frontend-crud:latest
    # command: python manage.py runserver 0.0.0.0:8000
    # volumes:
    #   - .:/code
    ports:
      - "8080:8080"
    # environment:
    #   - POSTGRES_NAME=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    # depends_on:
    #   - db